### ISSUE TITLE
Sweep: Address Console Error and troubleshoot

### ISSUE THREAD

**Issue by GravityPhone** [GravityPhone/Heady#1]
I attempted to run main_controller.py and I got this error:

Administrator in smarthat on  main [!] via 🐍 v3.9.0
❯ python .\main_controller.py
No module named 'Assistant'
Traceback (most recent call last):
  File "C:\smarthat\main_controller.py", line 10, in <module>
    from assistant_manager import AssistantManager
  File "C:\smarthat\assistant_manager.py", line 3, in <module>
    from Assistant import Assistant
ModuleNotFoundError: No module named 'Assistant'
Import error encountered.
Error message: No module named 'Assistant'
Traceback: Traceback (most recent call last):
  File "C:\smarthat\main_controller.py", line 10, in <module>
    from assistant_manager import AssistantManager
  File "C:\smarthat\assistant_manager.py", line 3, in <module>
    from Assistant import Assistant
ModuleNotFoundError: No module named 'Assistant'

Traceback (most recent call last):
  File "C:\smarthat\main_controller.py", line 24, in <module>
    vision_module = VisionModule(openai_api_key=os.getenv("OPENAI_API_KEY"))
NameError: name 'VisionModule' is not defined

---

Check any log files present to address the error,  carefully narrowing down the cause of the problem.

Also refer to the docs text file present, ProjectDocs.txt to understand what our project direction is, along with any code examples that we can use as clues to solve our problem.

Please address this directly, and consider what was supposed to happen if we didn't see this error.

You don't make huge changes just fix my error so I can give you the next error if there is one.

<details open>
<summary>Checklist</summary>

- [X] Modify `assistant_manager.py` ✓ https://github.com/GravityPhone/Heady/commit/c6dbe18df418e137d56b1ed6355705000b7c3022 [Edit](https://github.com/GravityPhone/Heady/edit/sweep/address_console_error_and_troubleshoot/assistant_manager.py)
- [X] Running GitHub Actions for `assistant_manager.py` ✓  [Edit](https://github.com/GravityPhone/Heady/edit/sweep/address_console_error_and_troubleshoot/assistant_manager.py)
- [X] Modify `main_controller.py` ! No changes made  [Edit](https://github.com/GravityPhone/Heady/edit/sweep/address_console_error_and_troubleshoot/main_controller.py)
- [X] Running GitHub Actions for `main_controller.py` ✗  [Edit](https://github.com/GravityPhone/Heady/edit/sweep/address_console_error_and_troubleshoot/main_controller.py)
</details>

**Comment by kevinlu1248** [comment]
sweep: Retry
